package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.ArrayList;

import antlr.collections.List;

/**
 * AirportsId generated by hbm2java
 */
public class AirportsId implements java.io.Serializable {

	private String iata;
	private String airport;
	private String city;
	private String state;
	private String country;
	private BigDecimal lat;
	private BigDecimal longi;

	public AirportsId() {
	}

	public AirportsId(String iata, String airport, String city, String state, String country, BigDecimal lat,
			BigDecimal longi) {
		this.iata = iata;
		this.airport = airport;
		this.city = city;
		this.state = state;
		this.country = country;
		this.lat = lat;
		this.longi = longi;
	}
	

	public String getIata() {
		return this.iata;
	}

	public void setIata(String iata) {
		this.iata = iata;
	}

	public String getAirport() {
		return this.airport;
	}

	public void setAirport(String airport) {
		this.airport = airport;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public BigDecimal getLat() {
		return this.lat;
	}

	public void setLat(BigDecimal lat) {
		this.lat = lat;
	}

	public BigDecimal getLongi() {
		return this.longi;
	}

	public void setLongi(BigDecimal longi) {
		this.longi = longi;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AirportsId))
			return false;
		AirportsId castOther = (AirportsId) other;

		return ((this.getIata() == castOther.getIata()) || (this.getIata() != null && castOther.getIata() != null
				&& this.getIata().equals(castOther.getIata())))
				&& ((this.getAirport() == castOther.getAirport()) || (this.getAirport() != null
						&& castOther.getAirport() != null && this.getAirport().equals(castOther.getAirport())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getState() == castOther.getState()) || (this.getState() != null
						&& castOther.getState() != null && this.getState().equals(castOther.getState())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getLat() == castOther.getLat()) || (this.getLat() != null && castOther.getLat() != null
						&& this.getLat().equals(castOther.getLat())))
				&& ((this.getLongi() == castOther.getLongi()) || (this.getLongi() != null
						&& castOther.getLongi() != null && this.getLongi().equals(castOther.getLongi())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIata() == null ? 0 : this.getIata().hashCode());
		result = 37 * result + (getAirport() == null ? 0 : this.getAirport().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getState() == null ? 0 : this.getState().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getLat() == null ? 0 : this.getLat().hashCode());
		result = 37 * result + (getLongi() == null ? 0 : this.getLongi().hashCode());
		return result;
	}

}
