package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Airports generated by hbm2java
 */
public class Airports implements java.io.Serializable {

	private AirportsId id;

	public Airports() {
	}

	public Airports(AirportsId id) {
		this.id = id;
	}

	public AirportsId getId() {
		return this.id;
	}

	public void setId(AirportsId id) {
		this.id = id;
	}

}
