package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Carriers generated by hbm2java
 */
public class Carriers implements java.io.Serializable {

	private CarriersId id;

	public Carriers() {
	}

	public Carriers(CarriersId id) {
		this.id = id;
	}

	public CarriersId getId() {
		return this.id;
	}

	public void setId(CarriersId id) {
		this.id = id;
	}

}
