package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Flights generated by hbm2java
 */
public class Flights implements java.io.Serializable {

	private FlightsId id;

	public Flights() {
	}

	public Flights(FlightsId id) {
		this.id = id;
	}

	public FlightsId getId() {
		return this.id;
	}

	public void setId(FlightsId id) {
		this.id = id;
	}

}
