package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * FlightsId generated by hbm2java
 */
public class FlightsId implements java.io.Serializable {

	private Integer year;
	private Integer month;
	private Integer dayofmonth;
	private Integer dayofweek;
	private Integer deptime;
	private Integer crsdeptime;
	private Integer arrtime;
	private Integer crsarrtime;
	private String uniquecarrier;
	private Integer flightnum;
	private String tailnum;
	private Integer actualelapsedtime;
	private Integer crselapsedtime;
	private Integer airtime;
	private Integer arrdelay;
	private Integer depdelay;
	private String origin;
	private String dest;
	private Integer distance;
	private Integer taxiin;
	private Integer taxiout;
	private String cancelled;
	private String cancellationcode;
	private Integer diverted;
	private Integer carrierdelay;
	private Integer weatherdelay;
	private Integer nasdelay;
	private Integer securitydelay;
	private Integer lateaircraftdelay;

	public FlightsId() {
	}

	public FlightsId(Integer year, Integer month, Integer dayofmonth, Integer dayofweek, Integer deptime,
			Integer crsdeptime, Integer arrtime, Integer crsarrtime, String uniquecarrier, Integer flightnum,
			String tailnum, Integer actualelapsedtime, Integer crselapsedtime, Integer airtime, Integer arrdelay,
			Integer depdelay, String origin, String dest, Integer distance, Integer taxiin, Integer taxiout,
			String cancelled, String cancellationcode, Integer diverted, Integer carrierdelay, Integer weatherdelay,
			Integer nasdelay, Integer securitydelay, Integer lateaircraftdelay) {
		this.year = year;
		this.month = month;
		this.dayofmonth = dayofmonth;
		this.dayofweek = dayofweek;
		this.deptime = deptime;
		this.crsdeptime = crsdeptime;
		this.arrtime = arrtime;
		this.crsarrtime = crsarrtime;
		this.uniquecarrier = uniquecarrier;
		this.flightnum = flightnum;
		this.tailnum = tailnum;
		this.actualelapsedtime = actualelapsedtime;
		this.crselapsedtime = crselapsedtime;
		this.airtime = airtime;
		this.arrdelay = arrdelay;
		this.depdelay = depdelay;
		this.origin = origin;
		this.dest = dest;
		this.distance = distance;
		this.taxiin = taxiin;
		this.taxiout = taxiout;
		this.cancelled = cancelled;
		this.cancellationcode = cancellationcode;
		this.diverted = diverted;
		this.carrierdelay = carrierdelay;
		this.weatherdelay = weatherdelay;
		this.nasdelay = nasdelay;
		this.securitydelay = securitydelay;
		this.lateaircraftdelay = lateaircraftdelay;
	}

	public Integer getYear() {
		return this.year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getMonth() {
		return this.month;
	}

	public void setMonth(Integer month) {
		this.month = month;
	}

	public Integer getDayofmonth() {
		return this.dayofmonth;
	}

	public void setDayofmonth(Integer dayofmonth) {
		this.dayofmonth = dayofmonth;
	}

	public Integer getDayofweek() {
		return this.dayofweek;
	}

	public void setDayofweek(Integer dayofweek) {
		this.dayofweek = dayofweek;
	}

	public Integer getDeptime() {
		return this.deptime;
	}

	public void setDeptime(Integer deptime) {
		this.deptime = deptime;
	}

	public Integer getCrsdeptime() {
		return this.crsdeptime;
	}

	public void setCrsdeptime(Integer crsdeptime) {
		this.crsdeptime = crsdeptime;
	}

	public Integer getArrtime() {
		return this.arrtime;
	}

	public void setArrtime(Integer arrtime) {
		this.arrtime = arrtime;
	}

	public Integer getCrsarrtime() {
		return this.crsarrtime;
	}

	public void setCrsarrtime(Integer crsarrtime) {
		this.crsarrtime = crsarrtime;
	}

	public String getUniquecarrier() {
		return this.uniquecarrier;
	}

	public void setUniquecarrier(String uniquecarrier) {
		this.uniquecarrier = uniquecarrier;
	}

	public Integer getFlightnum() {
		return this.flightnum;
	}

	public void setFlightnum(Integer flightnum) {
		this.flightnum = flightnum;
	}

	public String getTailnum() {
		return this.tailnum;
	}

	public void setTailnum(String tailnum) {
		this.tailnum = tailnum;
	}

	public Integer getActualelapsedtime() {
		return this.actualelapsedtime;
	}

	public void setActualelapsedtime(Integer actualelapsedtime) {
		this.actualelapsedtime = actualelapsedtime;
	}

	public Integer getCrselapsedtime() {
		return this.crselapsedtime;
	}

	public void setCrselapsedtime(Integer crselapsedtime) {
		this.crselapsedtime = crselapsedtime;
	}

	public Integer getAirtime() {
		return this.airtime;
	}

	public void setAirtime(Integer airtime) {
		this.airtime = airtime;
	}

	public Integer getArrdelay() {
		return this.arrdelay;
	}

	public void setArrdelay(Integer arrdelay) {
		this.arrdelay = arrdelay;
	}

	public Integer getDepdelay() {
		return this.depdelay;
	}

	public void setDepdelay(Integer depdelay) {
		this.depdelay = depdelay;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDest() {
		return this.dest;
	}

	public void setDest(String dest) {
		this.dest = dest;
	}

	public Integer getDistance() {
		return this.distance;
	}

	public void setDistance(Integer distance) {
		this.distance = distance;
	}

	public Integer getTaxiin() {
		return this.taxiin;
	}

	public void setTaxiin(Integer taxiin) {
		this.taxiin = taxiin;
	}

	public Integer getTaxiout() {
		return this.taxiout;
	}

	public void setTaxiout(Integer taxiout) {
		this.taxiout = taxiout;
	}

	public String getCancelled() {
		return this.cancelled;
	}

	public void setCancelled(String cancelled) {
		this.cancelled = cancelled;
	}

	public String getCancellationcode() {
		return this.cancellationcode;
	}

	public void setCancellationcode(String cancellationcode) {
		this.cancellationcode = cancellationcode;
	}

	public Integer getDiverted() {
		return this.diverted;
	}

	public void setDiverted(Integer diverted) {
		this.diverted = diverted;
	}

	public Integer getCarrierdelay() {
		return this.carrierdelay;
	}

	public void setCarrierdelay(Integer carrierdelay) {
		this.carrierdelay = carrierdelay;
	}

	public Integer getWeatherdelay() {
		return this.weatherdelay;
	}

	public void setWeatherdelay(Integer weatherdelay) {
		this.weatherdelay = weatherdelay;
	}

	public Integer getNasdelay() {
		return this.nasdelay;
	}

	public void setNasdelay(Integer nasdelay) {
		this.nasdelay = nasdelay;
	}

	public Integer getSecuritydelay() {
		return this.securitydelay;
	}

	public void setSecuritydelay(Integer securitydelay) {
		this.securitydelay = securitydelay;
	}

	public Integer getLateaircraftdelay() {
		return this.lateaircraftdelay;
	}

	public void setLateaircraftdelay(Integer lateaircraftdelay) {
		this.lateaircraftdelay = lateaircraftdelay;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FlightsId))
			return false;
		FlightsId castOther = (FlightsId) other;

		return ((this.getYear() == castOther.getYear()) || (this.getYear() != null && castOther.getYear() != null
				&& this.getYear().equals(castOther.getYear())))
				&& ((this.getMonth() == castOther.getMonth()) || (this.getMonth() != null
						&& castOther.getMonth() != null && this.getMonth().equals(castOther.getMonth())))
				&& ((this.getDayofmonth() == castOther.getDayofmonth()) || (this.getDayofmonth() != null
						&& castOther.getDayofmonth() != null && this.getDayofmonth().equals(castOther.getDayofmonth())))
				&& ((this.getDayofweek() == castOther.getDayofweek()) || (this.getDayofweek() != null
						&& castOther.getDayofweek() != null && this.getDayofweek().equals(castOther.getDayofweek())))
				&& ((this.getDeptime() == castOther.getDeptime()) || (this.getDeptime() != null
						&& castOther.getDeptime() != null && this.getDeptime().equals(castOther.getDeptime())))
				&& ((this.getCrsdeptime() == castOther.getCrsdeptime()) || (this.getCrsdeptime() != null
						&& castOther.getCrsdeptime() != null && this.getCrsdeptime().equals(castOther.getCrsdeptime())))
				&& ((this.getArrtime() == castOther.getArrtime()) || (this.getArrtime() != null
						&& castOther.getArrtime() != null && this.getArrtime().equals(castOther.getArrtime())))
				&& ((this.getCrsarrtime() == castOther.getCrsarrtime()) || (this.getCrsarrtime() != null
						&& castOther.getCrsarrtime() != null && this.getCrsarrtime().equals(castOther.getCrsarrtime())))
				&& ((this.getUniquecarrier() == castOther.getUniquecarrier())
						|| (this.getUniquecarrier() != null && castOther.getUniquecarrier() != null
								&& this.getUniquecarrier().equals(castOther.getUniquecarrier())))
				&& ((this.getFlightnum() == castOther.getFlightnum()) || (this.getFlightnum() != null
						&& castOther.getFlightnum() != null && this.getFlightnum().equals(castOther.getFlightnum())))
				&& ((this.getTailnum() == castOther.getTailnum()) || (this.getTailnum() != null
						&& castOther.getTailnum() != null && this.getTailnum().equals(castOther.getTailnum())))
				&& ((this.getActualelapsedtime() == castOther.getActualelapsedtime())
						|| (this.getActualelapsedtime() != null && castOther.getActualelapsedtime() != null
								&& this.getActualelapsedtime().equals(castOther.getActualelapsedtime())))
				&& ((this.getCrselapsedtime() == castOther.getCrselapsedtime())
						|| (this.getCrselapsedtime() != null && castOther.getCrselapsedtime() != null
								&& this.getCrselapsedtime().equals(castOther.getCrselapsedtime())))
				&& ((this.getAirtime() == castOther.getAirtime()) || (this.getAirtime() != null
						&& castOther.getAirtime() != null && this.getAirtime().equals(castOther.getAirtime())))
				&& ((this.getArrdelay() == castOther.getArrdelay()) || (this.getArrdelay() != null
						&& castOther.getArrdelay() != null && this.getArrdelay().equals(castOther.getArrdelay())))
				&& ((this.getDepdelay() == castOther.getDepdelay()) || (this.getDepdelay() != null
						&& castOther.getDepdelay() != null && this.getDepdelay().equals(castOther.getDepdelay())))
				&& ((this.getOrigin() == castOther.getOrigin()) || (this.getOrigin() != null
						&& castOther.getOrigin() != null && this.getOrigin().equals(castOther.getOrigin())))
				&& ((this.getDest() == castOther.getDest()) || (this.getDest() != null && castOther.getDest() != null
						&& this.getDest().equals(castOther.getDest())))
				&& ((this.getDistance() == castOther.getDistance()) || (this.getDistance() != null
						&& castOther.getDistance() != null && this.getDistance().equals(castOther.getDistance())))
				&& ((this.getTaxiin() == castOther.getTaxiin()) || (this.getTaxiin() != null
						&& castOther.getTaxiin() != null && this.getTaxiin().equals(castOther.getTaxiin())))
				&& ((this.getTaxiout() == castOther.getTaxiout()) || (this.getTaxiout() != null
						&& castOther.getTaxiout() != null && this.getTaxiout().equals(castOther.getTaxiout())))
				&& ((this.getCancelled() == castOther.getCancelled()) || (this.getCancelled() != null
						&& castOther.getCancelled() != null && this.getCancelled().equals(castOther.getCancelled())))
				&& ((this.getCancellationcode() == castOther.getCancellationcode())
						|| (this.getCancellationcode() != null && castOther.getCancellationcode() != null
								&& this.getCancellationcode().equals(castOther.getCancellationcode())))
				&& ((this.getDiverted() == castOther.getDiverted()) || (this.getDiverted() != null
						&& castOther.getDiverted() != null && this.getDiverted().equals(castOther.getDiverted())))
				&& ((this.getCarrierdelay() == castOther.getCarrierdelay())
						|| (this.getCarrierdelay() != null && castOther.getCarrierdelay() != null
								&& this.getCarrierdelay().equals(castOther.getCarrierdelay())))
				&& ((this.getWeatherdelay() == castOther.getWeatherdelay())
						|| (this.getWeatherdelay() != null && castOther.getWeatherdelay() != null
								&& this.getWeatherdelay().equals(castOther.getWeatherdelay())))
				&& ((this.getNasdelay() == castOther.getNasdelay()) || (this.getNasdelay() != null
						&& castOther.getNasdelay() != null && this.getNasdelay().equals(castOther.getNasdelay())))
				&& ((this.getSecuritydelay() == castOther.getSecuritydelay())
						|| (this.getSecuritydelay() != null && castOther.getSecuritydelay() != null
								&& this.getSecuritydelay().equals(castOther.getSecuritydelay())))
				&& ((this.getLateaircraftdelay() == castOther.getLateaircraftdelay())
						|| (this.getLateaircraftdelay() != null && castOther.getLateaircraftdelay() != null
								&& this.getLateaircraftdelay().equals(castOther.getLateaircraftdelay())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getYear() == null ? 0 : this.getYear().hashCode());
		result = 37 * result + (getMonth() == null ? 0 : this.getMonth().hashCode());
		result = 37 * result + (getDayofmonth() == null ? 0 : this.getDayofmonth().hashCode());
		result = 37 * result + (getDayofweek() == null ? 0 : this.getDayofweek().hashCode());
		result = 37 * result + (getDeptime() == null ? 0 : this.getDeptime().hashCode());
		result = 37 * result + (getCrsdeptime() == null ? 0 : this.getCrsdeptime().hashCode());
		result = 37 * result + (getArrtime() == null ? 0 : this.getArrtime().hashCode());
		result = 37 * result + (getCrsarrtime() == null ? 0 : this.getCrsarrtime().hashCode());
		result = 37 * result + (getUniquecarrier() == null ? 0 : this.getUniquecarrier().hashCode());
		result = 37 * result + (getFlightnum() == null ? 0 : this.getFlightnum().hashCode());
		result = 37 * result + (getTailnum() == null ? 0 : this.getTailnum().hashCode());
		result = 37 * result + (getActualelapsedtime() == null ? 0 : this.getActualelapsedtime().hashCode());
		result = 37 * result + (getCrselapsedtime() == null ? 0 : this.getCrselapsedtime().hashCode());
		result = 37 * result + (getAirtime() == null ? 0 : this.getAirtime().hashCode());
		result = 37 * result + (getArrdelay() == null ? 0 : this.getArrdelay().hashCode());
		result = 37 * result + (getDepdelay() == null ? 0 : this.getDepdelay().hashCode());
		result = 37 * result + (getOrigin() == null ? 0 : this.getOrigin().hashCode());
		result = 37 * result + (getDest() == null ? 0 : this.getDest().hashCode());
		result = 37 * result + (getDistance() == null ? 0 : this.getDistance().hashCode());
		result = 37 * result + (getTaxiin() == null ? 0 : this.getTaxiin().hashCode());
		result = 37 * result + (getTaxiout() == null ? 0 : this.getTaxiout().hashCode());
		result = 37 * result + (getCancelled() == null ? 0 : this.getCancelled().hashCode());
		result = 37 * result + (getCancellationcode() == null ? 0 : this.getCancellationcode().hashCode());
		result = 37 * result + (getDiverted() == null ? 0 : this.getDiverted().hashCode());
		result = 37 * result + (getCarrierdelay() == null ? 0 : this.getCarrierdelay().hashCode());
		result = 37 * result + (getWeatherdelay() == null ? 0 : this.getWeatherdelay().hashCode());
		result = 37 * result + (getNasdelay() == null ? 0 : this.getNasdelay().hashCode());
		result = 37 * result + (getSecuritydelay() == null ? 0 : this.getSecuritydelay().hashCode());
		result = 37 * result + (getLateaircraftdelay() == null ? 0 : this.getLateaircraftdelay().hashCode());
		return result;
	}

}
