package prov.dao;
// Generated Jul 23, 2016 12:10:03 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tail generated by hbm2java
 */
public class Tail implements java.io.Serializable {

	private TailId id;

	public Tail() {
	}

	public Tail(TailId id) {
		this.id = id;
	}

	public TailId getId() {
		return this.id;
	}

	public void setId(TailId id) {
		this.id = id;
	}

}
