package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * Axisusage generated by hbm2java
 */
public class Axisusage implements java.io.Serializable {

	private int idaxisusage;
	private Axis axis;
	private Visualization visualization;
	private String typeusage;

	public Axisusage() {
	}

	public Axisusage(int idaxisusage, Axis axis, Visualization visualization) {
		this.idaxisusage = idaxisusage;
		this.axis = axis;
		this.visualization = visualization;
	}

	public Axisusage(int idaxisusage, Axis axis, Visualization visualization, String typeusage) {
		this.idaxisusage = idaxisusage;
		this.axis = axis;
		this.visualization = visualization;
		this.typeusage = typeusage;
	}

	public int getIdaxisusage() {
		return this.idaxisusage;
	}

	public void setIdaxisusage(int idaxisusage) {
		this.idaxisusage = idaxisusage;
	}

	public Axis getAxis() {
		return this.axis;
	}

	public void setAxis(Axis axis) {
		this.axis = axis;
	}

	public Visualization getVisualization() {
		return this.visualization;
	}

	public void setVisualization(Visualization visualization) {
		this.visualization = visualization;
	}

	public String getTypeusage() {
		return this.typeusage;
	}

	public void setTypeusage(String typeusage) {
		this.typeusage = typeusage;
	}

}
