package evoDb;



import java.util.HashSet;
import java.util.Set;

/**
 * Axis generated by hbm2java
 */
public class Axis implements java.io.Serializable {

	private int idaxis;
	private Scale scale;
	private String tick;
	private String title;
	private String type;
	private Set axisusages = new HashSet(0);

	public Axis() {
	}

	public Axis(int idaxis) {
		this.idaxis = idaxis;
	}

	public Axis(int idaxis, Scale scale, String tick, String title, String type, Set axisusages) {
		this.idaxis = idaxis;
		this.scale = scale;
		this.tick = tick;
		this.title = title;
		this.type = type;
		this.axisusages = axisusages;
	}

	public int getIdaxis() {
		return this.idaxis;
	}

	public void setIdaxis(int idaxis) {
		this.idaxis = idaxis;
	}

	public Scale getScale() {
		return this.scale;
	}

	public void setScale(Scale scale) {
		this.scale = scale;
	}

	public String getTick() {
		return this.tick;
	}

	public void setTick(String tick) {
		this.tick = tick;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Set getAxisusages() {
		return this.axisusages;
	}

	public void setAxisusages(Set axisusages) {
		this.axisusages = axisusages;
	}

}
