package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * Channelusage generated by hbm2java
 */
public class Channelusage implements java.io.Serializable {

	private int idchannelusage;
	private Channel channel;
	private Mark mark;
	private String usagetype;

	public Channelusage() {
	}

	public Channelusage(int idchannelusage, Channel channel, Mark mark) {
		this.idchannelusage = idchannelusage;
		this.channel = channel;
		this.mark = mark;
	}

	public Channelusage(int idchannelusage, Channel channel, Mark mark, String usagetype) {
		this.idchannelusage = idchannelusage;
		this.channel = channel;
		this.mark = mark;
		this.usagetype = usagetype;
	}

	public int getIdchannelusage() {
		return this.idchannelusage;
	}

	public void setIdchannelusage(int idchannelusage) {
		this.idchannelusage = idchannelusage;
	}

	public Channel getChannel() {
		return this.channel;
	}

	public void setChannel(Channel channel) {
		this.channel = channel;
	}

	public Mark getMark() {
		return this.mark;
	}

	public void setMark(Mark mark) {
		this.mark = mark;
	}

	public String getUsagetype() {
		return this.usagetype;
	}

	public void setUsagetype(String usagetype) {
		this.usagetype = usagetype;
	}

}
