package evoDb;

// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Mark generated by hbm2java
 */
public class Mark implements java.io.Serializable {

	private int idmark;
	private Visualization visualization;
	private String marktype;
	private Set channelusages = new HashSet(0);

	public Mark() {
	}

	public Mark(int idmark) {
		this.idmark = idmark;
	}

	public Mark(int idmark, Visualization visualization, String marktype, Set channelusages) {
		this.idmark = idmark;
		this.visualization = visualization;
		this.marktype = marktype;
		this.channelusages = channelusages;
	}

	public int getIdmark() {
		return this.idmark;
	}

	public void setIdmark(int idmark) {
		this.idmark = idmark;
	}

	public Visualization getVisualization() {
		return this.visualization;
	}

	public void setVisualization(Visualization visualization) {
		this.visualization = visualization;
	}

	public String getMarktype() {
		return this.marktype;
	}

	public void setMarktype(String marktype) {
		this.marktype = marktype;
	}

	public Set getChannelusages() {
		return this.channelusages;
	}

	public void setChannelusages(Set channelusages) {
		this.channelusages = channelusages;
	}

}
