package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * QueryFromtable generated by hbm2java
 */
public class QueryFromtable implements java.io.Serializable {

	private int FId;
	private String froms;
	private int QId;

	public QueryFromtable() {
	}

	public QueryFromtable(int FId, int QId) {
		this.FId = FId;
		this.QId = QId;
	}

	public QueryFromtable(int FId, String froms, int QId) {
		this.FId = FId;
		this.froms = froms;
		this.QId = QId;
	}

	public int getFId() {
		return this.FId;
	}

	public void setFId(int FId) {
		this.FId = FId;
	}

	public String getFroms() {
		return this.froms;
	}

	public void setFroms(String froms) {
		this.froms = froms;
	}

	public int getQId() {
		return this.QId;
	}

	public void setQId(int QId) {
		this.QId = QId;
	}

}
