package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Querytable generated by hbm2java
 */
public class Querytable implements java.io.Serializable {

	private int idquery;
	private String datasetname;
	private Serializable transformation;
	private Serializable datasetvalue;
	private String literal;
	private Set visualizations = new HashSet(0);

	public Querytable() {
	}

	public Querytable(int idquery) {
		this.idquery = idquery;
	}

	public Querytable(int idquery, String datasetname, Serializable transformation, Serializable datasetvalue,
			String literal, Set visualizations) {
		this.idquery = idquery;
		this.datasetname = datasetname;
		this.transformation = transformation;
		this.datasetvalue = datasetvalue;
		this.literal = literal;
		this.visualizations = visualizations;
	}

	public int getIdquery() {
		return this.idquery;
	}

	public void setIdquery(int idquery) {
		this.idquery = idquery;
	}

	public String getDatasetname() {
		return this.datasetname;
	}

	public void setDatasetname(String datasetname) {
		this.datasetname = datasetname;
	}

	public Serializable getTransformation() {
		return this.transformation;
	}

	public void setTransformation(Serializable transformation) {
		this.transformation = transformation;
	}

	public Serializable getDatasetvalue() {
		return this.datasetvalue;
	}

	public void setDatasetvalue(Serializable datasetvalue) {
		this.datasetvalue = datasetvalue;
	}

	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	public Set getVisualizations() {
		return this.visualizations;
	}

	public void setVisualizations(Set visualizations) {
		this.visualizations = visualizations;
	}

}
