package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

/**
 * QuerySelecttable generated by hbm2java
 */
public class QuerySelecttable implements java.io.Serializable {

	private int SId;
	private String dimension;
	private int QId;

	public QuerySelecttable() {
	}

	public QuerySelecttable(int SId, int QId) {
		this.SId = SId;
		this.QId = QId;
	}

	public QuerySelecttable(int SId, String dimension, int QId) {
		this.SId = SId;
		this.dimension = dimension;
		this.QId = QId;
	}

	public int getSId() {
		return this.SId;
	}

	public void setSId(int SId) {
		this.SId = SId;
	}

	public String getDimension() {
		return this.dimension;
	}

	public void setDimension(String dimension) {
		this.dimension = dimension;
	}

	public int getQId() {
		return this.QId;
	}

	public void setQId(int QId) {
		this.QId = QId;
	}

}
