package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Scale generated by hbm2java
 */
public class Scale implements java.io.Serializable {

	private int idscale;
	private Dataset dataset;
	private String typescale;
	private String namescale;
	private String fielddom;
	private String fieldrange;
	private String literal;
	private Set channels = new HashSet(0);
	private Set axises = new HashSet(0);

	public Scale() {
	}

	public Scale(int idscale, Dataset dataset) {
		this.idscale = idscale;
		this.dataset = dataset;
	}

	public Scale(int idscale, Dataset dataset, String typescale, String namescale, String fielddom, String fieldrange,
			String literal, Set channels, Set axises) {
		this.idscale = idscale;
		this.dataset = dataset;
		this.typescale = typescale;
		this.namescale = namescale;
		this.fielddom = fielddom;
		this.fieldrange = fieldrange;
		this.literal = literal;
		this.channels = channels;
		this.axises = axises;
	}

	public int getIdscale() {
		return this.idscale;
	}

	public void setIdscale(int idscale) {
		this.idscale = idscale;
	}

	public Dataset getDataset() {
		return this.dataset;
	}

	public void setDataset(Dataset dataset) {
		this.dataset = dataset;
	}

	public String getTypescale() {
		return this.typescale;
	}

	public void setTypescale(String typescale) {
		this.typescale = typescale;
	}

	public String getNamescale() {
		return this.namescale;
	}

	public void setNamescale(String namescale) {
		this.namescale = namescale;
	}

	public String getFielddom() {
		return this.fielddom;
	}

	public void setFielddom(String fielddom) {
		this.fielddom = fielddom;
	}

	public String getFieldrange() {
		return this.fieldrange;
	}

	public void setFieldrange(String fieldrange) {
		this.fieldrange = fieldrange;
	}

	public String getLiteral() {
		return this.literal;
	}

	public void setLiteral(String literal) {
		this.literal = literal;
	}

	public Set getChannels() {
		return this.channels;
	}

	public void setChannels(Set channels) {
		this.channels = channels;
	}

	public Set getAxises() {
		return this.axises;
	}

	public void setAxises(Set axises) {
		this.axises = axises;
	}

}
