package evoDb;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Visualization generated by hbm2java
 */
public class Visualization implements java.io.Serializable {

	private int idvisualization;
	private Querytable querytable;
	private Integer width;
	private Integer length;
	private Set axisusages = new HashSet(0);
	private Set marks = new HashSet(0);

	public Visualization() {
	}

	public Visualization(int idvisualization) {
		this.idvisualization = idvisualization;
	}

	public Visualization(int idvisualization, Querytable querytable, Integer width, Integer length, Set axisusages,
			Set marks) {
		this.idvisualization = idvisualization;
		this.querytable = querytable;
		this.width = width;
		this.length = length;
		this.axisusages = axisusages;
		this.marks = marks;
	}

	public int getIdvisualization() {
		return this.idvisualization;
	}

	public void setIdvisualization(int idvisualization) {
		this.idvisualization = idvisualization;
	}

	public Querytable getQuerytable() {
		return this.querytable;
	}

	public void setQuerytable(Querytable querytable) {
		this.querytable = querytable;
	}

	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public Set getAxisusages() {
		return this.axisusages;
	}

	public void setAxisusages(Set axisusages) {
		this.axisusages = axisusages;
	}

	public Set getMarks() {
		return this.marks;
	}

	public void setMarks(Set marks) {
		this.marks = marks;
	}

}
