package prov.mybean;
// default package
// Generated Jan 8, 2018 2:36:58 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Visualization generated by hbm2java
 */
public class VisualizationBean implements java.io.Serializable {

	private int idvisualization;
	private Integer width;
	private Integer length;
	private List<Integer> axisID;
	private List<Integer> marksID;
	private List<Integer> scalesID;

	public VisualizationBean() {
	}

	public VisualizationBean(int idvisualization) {
		this.idvisualization = idvisualization;
	}

	public VisualizationBean(int idvisualization,  Integer width, Integer length, List<Integer> axisusages,
			List<Integer> marks,List<Integer> scales) {
		this.idvisualization = idvisualization;
		this.width = width;
		this.length = length;
		this.axisID= axisusages;
		this.marksID = marks;
		this.scalesID=scales;
	}

	public int getIdvisualization() {
		return this.idvisualization;
	}

	public void setIdvisualization(int idvisualization) {
		this.idvisualization = idvisualization;
	}

	
	public Integer getWidth() {
		return this.width;
	}

	public void setWidth(Integer width) {
		this.width = width;
	}

	public Integer getLength() {
		return this.length;
	}

	public void setLength(Integer length) {
		this.length = length;
	}

	public List<Integer> getAxisusages() {
		return this.axisID;
	}

	public void setAxisusages(List<Integer> axisusages) {
		this.axisID = axisusages;
	}

	

	public List<Integer> getAxisID() {
		return axisID;
	}

	public List<Integer> getMarksID() {
		return marksID;
	}

	public List<Integer> getScalesID() {
		return scalesID;
	}

	public void setAxisID(List<Integer> axisID) {
		this.axisID = axisID;
	}

	public void setMarksID(List<Integer> marksID) {
		this.marksID = marksID;
	}

	public void setScalesID(List<Integer> scalesID) {
		this.scalesID = scalesID;
	}

	
	
	
	
}
